variables:
  rpm_release: "0.$CI_PIPELINE_ID"
  specfile: $project.spec
  other_repos: ${s3_repo_url}redhawk-dependencies/redhawk-dependencies
  redhawk_version: '2.2.7'
  # The REDHAWK branch variable tracks the mainline branch from which a topic
  # branch was forked, allowing it to still trigger that branch's test pipeline
  redhawk_branch: 'develop-2.2'
  # By default, pull dependencies from the REDHAWK branch, but should there be
  # a need to use a different set, override that here
  redhawk_deps: develop-2.2-EVO_transition #$redhawk_branch
  commit: $CI_COMMIT_SHA
  datetime: ""

stages:
 - package-redhawk-codegen
 - package-bulkio-gpp
 - package-burstio-fei
 - deploy

.rpmbuild: &rpmbuild
  image: ${docker_registry}toa/docker:latest-git
  tags:
    - docker
    - redhawk
  script:
    # Use RPM release from specfile if this is a tag
    - if [ -n "$CI_COMMIT_TAG" ]; then rpm_release=""; fi
    - if [ -f output/repo.tar.gz ]; then cd output; tar xvf repo.tar.gz; cd -; cp -r output $project; fi
    - cd $project
    - echo "commit hash => ${commit:0:8}"
    - datetime=$(git show -s --format=%cd ${commit})
    - echo "commit date => ${datetime}"
    - printf "FROM ${docker_registry}${rpmbuild_repository}toa/rpmbuild:${dist}-${arch}-onbuild" > Dockerfile
    # Don't build redhawk tests as part of rpmbuild to save time
    - if [ "$project" == "redhawk" ]; then sed -i 's|testing||' src/Makefile.am; fi
    - proj_lower=$(echo $project | tr '[:upper:]' '[:lower:]')
    - safe_ref=$(echo ${CI_COMMIT_REF_NAME} | tr -d /| tr '[:upper:]' '[:lower:]')
    - docker login ${docker_registry} -u ${docker_user} -p ${docker_password}
    - docker build --tag=${docker_registry}toa/redhawk-rpmbuild:$proj_lower-$safe_ref-${dist}-${arch}
                   --pull
                   --no-cache
                   --build-arg "commit=${commit:0:8}"
                   --build-arg "datetime=${datetime}"
                   --build-arg "project=$project"
                   --build-arg "arch=$arch"
                   --build-arg "spec_file=$specfile"
                   --build-arg "rpm_release=$rpm_release"
                   --build-arg "other_repos=${other_repos}/yum/${redhawk_deps}/$dist/$arch"
                   --build-arg "local_repo=$local_repo" .
    # Create a yum repository from the packages we just built and any packages we've built in a previous stage
    - id=$(docker create -it ${docker_registry}toa/redhawk-rpmbuild:$proj_lower-$safe_ref-$dist-$arch bash -lc 'mkdir -p /tmp/repo;
                                                for file in `find /usr/src/yum /root/rpmbuild/RPMS -name '*.rpm'`; do
                                                cp -v $file /tmp/repo;
                                                done;
                                                cd /tmp/repo;
                                                createrepo .;
                                                tar czf repo.tar.gz *')
    - docker start -a $id
    # Cleanup any previous output we've inherited
    - cd $CI_PROJECT_DIR
    - rm -rf output && mkdir output
    - docker cp $id:/tmp/repo/repo.tar.gz output/repo.tar.gz
    - docker rm -f $id || true
    - cd output
    - tar xf repo.tar.gz
    - cd $CI_PROJECT_DIR
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - output/
    expire_in: 2 days
  except:
    - master
    - /^(\d+\.)?(\d+)?(\.\d+)$/

redhawk:el7:
  stage: package-redhawk-codegen
  variables:
    dist: el7
    arch: x86_64
    project: redhawk
    specfile: src/releng/redhawk.spec
    local_repo: ""
  <<: *rpmbuild

redhawk-codegen:el7:
  stage: package-redhawk-codegen
  variables:
    dist: el7
    arch: x86_64
    project: redhawk-codegen
    local_repo: ""
  <<: *rpmbuild

bulkio:el7:
  stage: package-bulkio-gpp
  dependencies:
    - redhawk:el7
  variables:
    dist: el7
    arch: x86_64
    project: bulkioInterfaces
    local_repo: output
  <<: *rpmbuild

gpp:el7:
  stage: package-bulkio-gpp
  dependencies:
    - redhawk:el7
  variables:
    dist: el7
    arch: x86_64
    project: GPP
    local_repo: output
  <<: *rpmbuild

burstio:el7:
  stage: package-burstio-fei
  dependencies:
    - bulkio:el7
  variables:
    dist: el7
    arch: x86_64
    project: burstioInterfaces
    local_repo: output
  <<: *rpmbuild

frontend:el7:
  stage: package-burstio-fei
  dependencies:
    - bulkio:el7
  variables:
    dist: el7
    arch: x86_64
    project: frontendInterfaces
    local_repo: output
  <<: *rpmbuild

# Trigger separate tests pipeline
.trigger-common: &trigger-common
  image: ${docker_registry}toa/centos:centos7
  stage: deploy
  dependencies: []
  variables:
    # Default to the redhawk branch named in the global variables, which will
    # typically be a develop branch. Feature branches trigger a test pipeline
    # using the develop branch from which they were forked unless overridden
    # here.
    redhawk_testing_ref: $redhawk_branch
  script:
    - curl --insecure -X POST -F ref=$redhawk_testing_ref
                              -F token=$test_token
                              -F "variables[triggering_ref]=$CI_COMMIT_SHA"
                              -F "variables[triggering_ref_name]=$CI_COMMIT_REF_NAME"
                              -F "variables[triggering_ref_slug]=$CI_COMMIT_REF_SLUG"
                              $test_url

# For bug/feature branches, require the developer to manually trigger the tests
test-trigger:branch:
  <<: *trigger-common
  when: manual
  only:
    - branches
  except:
    - master
    - /^develop.*$/

# For develop branches, automatically trigger test pipeline
test-trigger:develop:
  <<: *trigger-common
  only:
    - /^develop.*$/

test-trigger:release:
  image: ${docker_registry}toa/centos:centos7
  stage: deploy
  dependencies: []
  script:
    - curl --insecure -X POST -F ref=$CI_COMMIT_REF_NAME"
                              -F token=$test_token
                              -F "variables[triggering_ref]=$CI_COMMIT_SHA"
                              -F "variables[triggering_ref_name]=$CI_COMMIT_REF_NAME"
                              -F "variables[output_name]=$CI_COMMIT_REF_NAME"
                              $test_url
  only:
    - tags
  except:
    - /^(\d+\.)?(\d+)?(\.\d+)$/

.s3: &s3
  image: ${docker_registry}toa/rpmbuild:$dist-$arch-onbuild
  stage: deploy
  tags:
    - docker
    - redhawk
  script:
    - CI_COMMIT_REF_SLUG_NO_RC=${CI_COMMIT_REF_SLUG%-rc[0-9]*};
    - mkdir -p $arch
    - for file in `find output -name *.rpm`; do
        cp $file $arch;
      done
    - createrepo $arch
    - ls -la $arch
    - /usr/bin/s3cmd sync -F -v --delete-removed $arch s3://${s3_bucket}/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yum/$CI_COMMIT_REF_SLUG/$dist/
    - if [ "$CI_COMMIT_REF_SLUG_NO_RC" != "$CI_COMMIT_REF_SLUG" ]; then
        /usr/bin/s3cmd sync -F -v --delete-removed $arch s3://${s3_bucket}/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yum/$CI_COMMIT_REF_SLUG_NO_RC/$dist/;
      fi
    # Pull down dependencies to create aggregated "cf-and-deps" repo
    - mkdir -p cf-and-deps/$arch
    - printf "[redhawk-dependencies]\nname=REDHAWK dependencies\nbaseurl=${s3_repo_url}redhawk-dependencies/redhawk-dependencies/yum/$CI_COMMIT_REF_NAME/$dist/$arch\ns3_enabled=1\nregion=us-east-1\n" > /etc/yum.repos.d/redhawk-dependencies.repo
    - cat /etc/yum.repos.d/redhawk-dependencies.repo
    - yum clean all
    - reposync --plugins
               --download_path=tmp
               --newest-only
               --repoid=redhawk-dependencies
    - for file in `find tmp -name *.rpm`; do
        cp $file cf-and-deps/$arch;
      done
    - for file in `find output -name *.rpm`; do
        cp $file cf-and-deps/$arch;
      done
    - createrepo cf-and-deps/$arch
    - cd cf-and-deps
    - /usr/bin/s3cmd sync -F -v --delete-removed $arch s3://${s3_bucket}/$CI_PROJECT_NAMESPACE/cf-and-deps/yum/$CI_COMMIT_REF_SLUG/$dist/
  except:
    - master
    - /^(\d+\.)?(\d+)?(\.\d+)$/

deploy-el7:
  variables:
    dist: el7
    arch: x86_64
  dependencies:
    - redhawk:el7
    - bulkio:el7
    - burstio:el7
    - frontend:el7
    - gpp:el7
    - redhawk-codegen:el7
  <<: *s3
